In [1]:
import cv2
import matplotlib
from random import randint
import numpy as np

## pts_dst = pts_src * H_gt

In [2]:
pts_src = np.array([[141, 131], [480, 159], [493, 630],[64, 601]])

In [3]:
h_gt = np.random.randint(10, size=(3,3))

In [4]:
h_gt[2][2] = 1  # make the scale factor to 1
h_gt[2][0] = 0.1
h_gt[2][1] = 0.5

In [5]:
pts_homog = [np.append(pt,1) for pt in pts_src]  # extend to homogenous coordinate
pts_homog = np.asarray(pts_homog)

In [6]:
pts_homog = np.transpose(pts_homog)
pts_dts_gt_homog = np.matmul(h_gt,pts_homog)
pts_dts_gt_homog = np.transpose(pts_dts_gt_homog)

In [7]:
pts_dst_gt = [np.array([pt[0]/pt[2], pt[1]/pt[2]]) for pt in pts_dts_gt_homog] # convert back to pixcel coordinate
pts_dst_gt = np.asarray(pts_dst_gt)

In [8]:
pts_dst_gt

array([[ 525., 1533.],
       [ 637., 4640.],
       [2521., 5699.],
       [2405., 1780.]])

In [9]:
h, status = cv2.findHomography(pts_src, pts_dst_gt)

In [10]:
# the result should be same as h_gt
h

array([[1.68397545e-16, 4.00000000e+00, 1.00000000e+00],
       [9.00000000e+00, 2.00000000e+00, 2.00000000e+00],
       [7.49889187e-20, 3.27287728e-19, 1.00000000e+00]])

In [11]:
h_gt

array([[0, 4, 1],
       [9, 2, 2],
       [0, 0, 1]])

In [ ]:
'''
array([[3, 7, 4],              
       [5, 7, 4],
       [6, 3, 1]])

array([[ -6.26997755, -14.62459637,  -4.9216654 ],
       [-10.44768729, -14.62565906,  -4.23447605],
       [-12.53458838,  -6.27018818,   1.        ]])
       
'''

In [ ]:
'''
array([[0, 1, 9],
       [3, 2, 7],
       [7, 3, 1]])

array([[1.05613321e-04, 1.68869009e+00, 1.51246675e+01],
       [5.06619167e+00, 3.37769100e+00, 1.14730577e+01],
       [1.18209380e+01, 5.06679471e+00, 1.00000000e+00]])

'''

The observation is that when the "H[2][0] and H[2][1]" are too big (heavily scale) the matrix, the result will be bad